"use client";
import { useMemo, useState } from "react";
import { domains, subjects, taskDemands, levels } from "../data/wida";
import { strategies } from "../data/strategies";
import { buildPrompt, recommend, scoreToBand, snapshot } from "../lib/recommendations";
import type { Plan } from "../lib/types";

const demo: Plan = { grade:"4", scores:{Listening:4.2,Speaking:2.3,Reading:2.8,Writing:1.9}, subject:"Science", objective:"Explain how erosion changes Earth’s surface using evidence from a text.", demands:["Read a text","Discuss with classmates","Explain their thinking","Write a paragraph / extended response","Use evidence"], task:"Students will read a passage about erosion and answer the question: Explain how erosion changes Earth’s surface. Use evidence from the text to support your answer." };
const empty: Plan = { grade:"4", scores:{Listening:2.8,Speaking:2.1,Reading:3,Writing:1.9}, subject:"Science", objective:"", demands:[], task:"" };

function Logo(){return <div className="logo"><div className="logoMark" aria-hidden>◉</div><div><b>MY MULTILINGUAL<br/><span>CLASSROOM</span></b><small>Understand the learner.<br/>Scaffold the learning.</small></div></div>}
function Icon({children}:{children:React.ReactNode}){return <span className="icon" aria-hidden>{children}</span>}

function WorkflowStepper({step,setStep}:{step:number;setStep:(n:number)=>void}){
  return <nav className="stepper" aria-label="Plan progress">{["Learner","Task","Scaffold Plan","AI Prompt"].map((label,i)=><button key={label} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>setStep(i+1)}><span>{step>i+1?"✓":i+1}</span><em>{label}</em></button>)}</nav>
}

function DomainScoreCard({domain,value,onChange}:{domain:typeof domains[number];value:number;onChange:(n:number)=>void}){
  return <label className={`domain ${domain.color}`}><span className="domainIcon">{domain.icon}</span><b>{domain.name}</b><input aria-label={`${domain.name} score`} type="number" min="1" max="6" step="0.1" value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{value>=1&&value<=6?scoreToBand(value):"Enter 1.0–6.0"}</small></label>
}

function TeacherSnapshot({plan}:{plan:Plan}){return <div className="snapshot"><Icon>♣</Icon><div><b>What this profile suggests</b><p>{snapshot(plan.scores)}</p><small>WIDA scores are one source of information. Teacher observation, background knowledge, literacy experience, home languages, and the specific task also matter.</small></div></div>}

function Learner({plan,setPlan}:{plan:Plan;setPlan:(p:Plan)=>void}){
  return <section><div className="sectionHead"><div><span className="eyebrow">STEP 1</span><h1>Tell us about your learner</h1><p>Enter the learner’s most recent WIDA domain scores.</p></div><button className="secondary" onClick={()=>setPlan(demo)}>Load Demo Learner</button></div>
    <div className="privacy"><Icon>♢</Icon><div><b>Protect student privacy</b><p>Use scores and instructional information only. Do not enter names, IDs, medical information, or other identifying details.</p></div></div>
    <label className="field compact"><span>Grade</span><select value={plan.grade} onChange={e=>setPlan({...plan,grade:e.target.value})}>{["K","1","2","3","4","5"].map(x=><option key={x}>{x}</option>)}</select></label>
    <div className="domainGrid">{domains.map(d=><DomainScoreCard key={d.name} domain={d} value={plan.scores[d.name]} onChange={v=>setPlan({...plan,scores:{...plan.scores,[d.name]:v}})}/>)}</div>
    <TeacherSnapshot plan={plan}/>
  </section>
}

function Task({plan,setPlan}:{plan:Plan;setPlan:(p:Plan)=>void}){
  const toggle=(d:string)=>setPlan({...plan,demands:plan.demands.includes(d)?plan.demands.filter(x=>x!==d):[...plan.demands,d]});
  return <section><div className="sectionHead"><div><span className="eyebrow purpleText">STEP 2</span><h1>What are students doing?</h1><p>Describe the learning goal—not just the worksheet.</p></div></div>
    <div className="formTwo"><label className="field"><span>Subject</span><select value={plan.subject} onChange={e=>setPlan({...plan,subject:e.target.value})}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Learning objective</span><input value={plan.objective} onChange={e=>setPlan({...plan,objective:e.target.value})} placeholder="Explain how erosion changes Earth’s surface using evidence…"/></label></div>
    <fieldset><legend>What will students need to do? <small>Select all that apply</small></legend><div className="checks">{taskDemands.map(d=><label key={d} className={plan.demands.includes(d)?"selected":""}><input type="checkbox" checked={plan.demands.includes(d)} onChange={()=>toggle(d)}/><span>{d}</span></label>)}</div></fieldset>
    <label className="field"><span>Paste the task</span><textarea maxLength={5000} value={plan.task} onChange={e=>setPlan({...plan,task:e.target.value})} placeholder="Paste the assignment, directions, questions, or short text here."/><small className="count">{plan.task.length}/5000</small></label>
  </section>
}

function ScaffoldSection({tone,icon,title,children}:{tone:string;icon:string;title:string;children:React.ReactNode}){return <div className={`scaffold ${tone}`}><Icon>{icon}</Icon><div><h3>{title}</h3>{children}</div></div>}
function ScaffoldPlan({plan}:{plan:Plan}){
 const rec=recommend(plan);
 return <section><div className="sectionHead"><div><span className="eyebrow blueText">STEP 3</span><h1>Your scaffold plan</h1><p>A focused starting point. Use what helps; fade support as independence grows.</p></div></div>
   <div className="taskAnchor"><span>Built for this task</span><p>{plan.objective}</p><small>{plan.subject} · {plan.demands.slice(0,3).join(" · ")}{plan.demands.length>3?` · +${plan.demands.length-3} more`:""}</small></div>
   <ScaffoldSection tone="blue" icon="◎" title="Possible language demands to consider"><ul>{rec.demands.map(x=><li key={x}>This task asks the learner to use <b>{x.toLowerCase()}</b>.</li>)}</ul></ScaffoldSection>
   <div className="startFirst"><span>✦</span><div><h3>Start with these</h3><ol>{rec.priority.map(x=><li key={x}>{x}</li>)}</ol><small>The smallest useful set is usually the best place to begin.</small></div></div>
   <div className="planCols"><ScaffoldSection tone="green" icon="▣" title="Before the task"><ul>{rec.before.map(x=><li key={x}>{x}</li>)}</ul></ScaffoldSection><ScaffoldSection tone="orange" icon="☷" title="During the task"><ul>{rec.during.map(x=><li key={x}>{x}</li>)}</ul></ScaffoldSection></div>
   <ScaffoldSection tone="purple" icon="▰" title="Language support to provide"><div className="supportGrid"><div><b>Words drawn from this task</b><div className="chips">{rec.vocabulary.map(x=><span key={x}>{x}</span>)}</div></div><div><b>Frames matched to the task</b>{rec.frames.map(frame=><p key={frame}>“{frame}”</p>)}</div></div></ScaffoldSection>
   <ScaffoldSection tone="teal" icon="●" title="Student independence"><p>{rec.independence}</p></ScaffoldSection>
   <div className="reminder">★ <b>Scaffold the language, not the thinking.</b></div>
 </section>
}

function AIPromptBuilder({plan}:{plan:Plan}){const [text,setText]=useState(buildPrompt(plan));const [copied,setCopied]=useState(false); const copy=async()=>{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)};return <section><div className="sectionHead"><div><span className="eyebrow blueText">STEP 4</span><h1>Copy your AI prompt</h1><p>Edit anything you like, then paste it into your preferred AI tool.</p></div></div><div className="promptCard"><div className="promptNote"><Icon>◈</Icon><div><b>Keep student details private</b><p>This prompt contains only the instructional information entered here.</p></div></div><textarea className="prompt" value={text} onChange={e=>setText(e.target.value)}/><button className="primary copy" onClick={copy}>{copied?"✓ Copied":"▣ Copy Prompt"}</button></div></section>}

function QuickScaffold(){const [domain,setDomain]=useState("Writing"),[level,setLevel]=useState("2 — Emerging"),[subject,setSubject]=useState("Science"),[task,setTask]=useState("Explain thinking"),[show,setShow]=useState(false);const fields:{label:string;value:string;setter:(value:string)=>void;options:string[]}[]=[{label:"Domain",value:domain,setter:setDomain,options:["Listening","Speaking","Reading","Writing"]},{label:"Level",value:level,setter:setLevel,options:levels.map(x=>`${x.level} — ${x.name}`)},{label:"Subject",value:subject,setter:setSubject,options:subjects},{label:"Task type",value:task,setter:setTask,options:["Read a text","Join a discussion","Answer questions","Write sentences","Write a paragraph","Explain thinking","Use evidence","Give a presentation","Follow directions"]}];return <section><div className="sectionHead"><div><span className="eyebrow orangeText">TWO-MINUTE MODE</span><h1>Quick Scaffold</h1><p>I have two minutes. Help me support tomorrow’s lesson.</p></div></div><div className="quickForm">{fields.map(({label,value,setter,options})=><label className="field" key={label}><span>{label}</span><select value={value} onChange={e=>setter(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>)}</div><button className="primary" onClick={()=>setShow(true)}>Build Quick Scaffold</button>{show&&<div className="quickResult"><h2>Try these first</h2><ol><li>Preview a visual word bank with 5–8 essential {subject.toLowerCase()} terms.</li><li>Model one {task.toLowerCase()} response without supplying the answer.</li><li>Give the learner time for oral rehearsal with a partner.</li><li>Offer two optional language frames linked to the task.</li></ol><h3>Why these help</h3><p>They reduce the language-processing load while keeping the grade-level thinking intact.</p><h3>What to remove first</h3><p>Fade the sentence frames first, moving from partial frames to student-generated language.</p></div>}</section>}

function Library(){const cats=["All",...new Set(strategies.map(s=>s.category))];const [cat,setCat]=useState("All");return <section><div className="sectionHead"><div><span className="eyebrow purpleText">EXPLORE</span><h1>Scaffold library</h1><p>Practical supports for access, participation, and independence.</p></div></div><div className="filter" role="group" aria-label="Strategy categories">{cats.map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="libraryGrid">{strategies.filter(s=>cat==="All"||s.category===cat).map(s=><article className="strategy" key={s.name}><small>{s.category}</small><h3>{s.name}</h3><p>{s.what}</p><dl><dt>When it helps</dt><dd>{s.when}</dd><dt>Quick example</dt><dd>{s.example}</dd><dt>Domains</dt><dd>{s.domains}</dd></dl><div className="fade">↗ Fade it: {s.fade}</div></article>)}</div></section>}

function WidaGuide(){return <section><div className="sectionHead"><div><span className="eyebrow greenText">TEACHER GUIDE</span><h1>WIDA at a glance</h1><p>Use proficiency information as one part of a fuller picture of the learner.</p></div></div><div className="guideNote"><b>Proficiency levels describe developing use of English.</b> They are not measures of intelligence, content knowledge, motivation, or potential.</div><div className="levels">{levels.map(l=><article key={l.level}><span>{l.level}</span><div><h3>{l.name}</h3><b>The learner may be ready to…</b><p>{l.ready}.</p><b>The learner may benefit from…</b><p>{l.benefit}.</p><b>Teacher move</b><p>Offer purposeful support, observe the response, and fade it when ready.</p></div></article>)}</div></section>}

export default function App(){const [step,setStep]=useState(1),[view,setView]=useState("plan"),[plan,setPlan]=useState<Plan>(empty);const canContinue=step===1?Object.values(plan.scores).every(x=>x>=1&&x<=6):step===2?Boolean(plan.objective.trim()&&plan.task.trim()&&plan.demands.length):true;const reset=()=>{setPlan(empty);setStep(1);setView("plan")}; const content=useMemo(()=>step===1?<Learner plan={plan} setPlan={setPlan}/>:step===2?<Task plan={plan} setPlan={setPlan}/>:step===3?<ScaffoldPlan plan={plan}/>:<AIPromptBuilder key={buildPrompt(plan)} plan={plan}/>,[step,plan]);
return <div className="app"><aside><Logo/><nav className="sideNav"><small>START HERE</small>{[["plan","⌂","New Scaffold Plan"],["quick","ϟ","Quick Scaffold"],["library","▤","Scaffold Library"],["wida","ⓘ","WIDA Guide"]].map(([id,ic,label])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);if(id==="plan")setStep(1)}}><Icon>{ic}</Icon>{label}</button>)}</nav><div className="philosophy"><Icon>♥</Icon><div><b>High Challenge. High Support.</b><p>Keep the learning goal and provide the language support learners need to succeed.</p></div></div><button className="reset" onClick={reset}>↻ Reset plan</button></aside>
<main><header><div className="mobileLogo"><Logo/></div>{view==="plan"&&<WorkflowStepper step={step} setStep={setStep}/>}<button className="help" aria-label="Help">? <span>Help</span></button></header><div className="content">{view==="plan"?content:view==="quick"?<QuickScaffold/>:view==="library"?<Library/>:<WidaGuide/>}</div>{view==="plan"&&<div className="actions">{step>1?<button className="secondary" onClick={()=>setStep(step-1)}>← Back</button>:<span/>}<button className="primary" disabled={!canContinue} onClick={()=>setStep(Math.min(4,step+1))}>{step===4?"Prompt ready":step===2?"Build my scaffold plan":"Continue"} {step<4&&"→"}</button></div>}<footer><b>My Multilingual Classroom</b><span>WIDA-informed, teacher-guided, privacy-minded.</span></footer></main></div>}
